gateway:
  listenAddr: localhost:8080
  routes:
    - name: Service A
      context: /service-a
      target: http://localhost:8082
    - name: Service B
      context: /service-b
      target: http://localhost:8081